version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - api

  api:
    image: your-laravel-api-image  # Replace with your Laravel API image
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=your_database
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 